button_link:
  type: string
  default: "/"
button_target:
  default: "_blank"
  type: enum
  choices:
    - _blank
    - _self
show_on:
  default: "everywhere"
  type: enum
  choices:
    - homepage
    - latest/top/new/categories
    - everywhere
plugin_outlet:
  default: "above-site-header"
hide_on_mobile:
  default: false
